update terraform to use hash as comment per recommended guidelines
google/addlicense pull request #137
Opened 2023-01-13 21:28 UTC by verbanicm

Hashicorp documentation references using hash (`#`) as the default comment and is generally preferred to the long block comment style.

https://developer.hashicorp.com/terraform/language/syntax/configuration#comments

2023-01-15 23:56 UTC, willnorris requested changes
Look like a couple of unnecessary changes accidentally got included.  Could you back those out?  (or I can do it later when I have a little more time)

2023-01-15 23:56 UTC, willnorris commented on main_test.go
> +	if err := ioutil.WriteFile(f.Name(), []byte(contents), 0o644); err != nil {
extra typo?

2023-01-15 23:56 UTC, willnorris commented on main_test.go
> +			[]string{
unrelated change?

2023-01-16 02:25 UTC, verbanicm commented on main_test.go
> +			[]string{
gofmt/gofumpt auto formatting, reverted

2023-01-16 02:25 UTC, verbanicm commented on main_test.go
> +	if err := ioutil.WriteFile(f.Name(), []byte(contents), 0o644); err != nil {
gofmt/gofumpt auto formatting, reverted

2023-01-16 02:26 UTC, verbanicm commented
> Look like a couple of unnecessary changes accidentally got included. Could you back those out? (or I can do it later when I have a little more time)

Reverted those lines, auto formatter ftw!

2023-01-16 17:06 UTC, willnorris approved these changes

2023-01-16 17:07 UTC, merged

2023-01-16 20:35 UTC, verbanicm commented
Thanks @willnorris !